### ISSUE TITLE
Create MOODLE_34_STABLE branch and merge it from iarenaza:MOODLE_34_STABLE

### ISSUE THREAD

**Issue by iarenaza** [julenpardo/moodle-atto_multilang2#29]
As there isn't a MOODLE_34_STABLE branch yet, I'm unable to create a pull request for that branch.

Once the branch is created, I'll create a pull request for it.

**Comment by eljulians** [comment]
Hey Iñaki,

The branch is already created. You can make the pull request whenever you want. :)

**Comment by iarenaza** [comment]
Hi Julen,

given that you have already merged the pull request for MOODLE_34_STABLE branch (in issue #30), you can close this issue.
