### ISSUE TITLE
Disable language selection for students

### ISSUE THREAD

**Issue by eljulians** [julenpardo/moodle-atto_multilang2#3]
Emulating Iñaki Arenaza's functionality: https://github.com/iarenaza/moodle-tinymce_moodlelang2/commit/0bdaf93841855cdabbf7a06d2f68c372286ceaca

**Comment by abias** [comment]
+1 for solving this issue. It keeps me somehow from installing it on our Moodle site.

Thanks,
Alex

**Comment by eljulians** [comment]
Hi Alex,

Currently I'm too bussy with other plugin, but I have planned to return to these issues (this and the other where you commented), by the end of Easter Holidays.

Thank you for your interest,
Julen

**Comment by eljulians** [comment]
Fixed and merged to master, see commit df06018 and build nº 68.

**Comment by eljulians** [comment]
Hi @abias,

I've resolved this, but I think I will wait to the resolution of the tickets #4 and #8 to make the release.

Best regards,
Julen
