### ISSUE TITLE
Would it make sense to declare dependency on the filter?

### ISSUE THREAD

**Issue by mudrd8mz** [julenpardo/moodle-atto_multilang2#6]
It seems that technically, this Atto plugin does not need the filter. Yet I am wondering if it would be cleaner for admins if the dependency on the filter was explicitly declared in version.php

See `$plugin->dependencies` at https://docs.moodle.org/dev/version.php

**Comment by eljulians** [comment]
Hi @mudrd8mz, thanks for taking time to review the plugin.

You're right, even if the plugin does not technically need the filter, its use would not make sense without it. But taking into account that @iarenaza's [filter](https://github.com/iarenaza/moodle-filter_multilang2) is not published on the plugins directory, can I specify the dependency?

**Comment by mudrd8mz** [comment]
I discussed this case with other Moodle core developers and we all agree that the explicit dependency should be added. Good to see you agree with that too.

Yes, a dependency can be declared even on plugin not available in the plugins directory. Admins will have to provide the missing code manually as Moodle itself integrates with the plugins directory only. Alternatively @iarenaza may want to submit his filter into the plugins directory, too.

**Comment by eljulians** [comment]
Hi David, 

I've made the release on plugins directory with the dependency to [filter_multilang2](https://github.com/iarenaza/moodle-filter_multilang2).

I'm very glad you contributed to this plugin. :)

**Comment by iarenaza** [comment]
I've just opened and issue in the tracker to add the [filter_multilang2 plugin](https://github.com/iarenaza/moodle-filter_multilang2) to the plugins database.

If it gets approved, this should make it easier for other to install both plugins at the same time.

**Comment by mudrd8mz** [comment]
Thanks @iarenaza. Please note that https://docs.moodle.org/dev/Plugin_contribution#How_to_submit_code seems to be a bit outdated. You as the maintainer are basically supposed to submit your plugin into the plugins directory at https://moodle.org/plugins/registerplugin.php Sorry for the confusion.

**Comment by iarenaza** [comment]
@mudrd8mz Thanks for the heads up!

**Comment by mudrd8mz** [comment]
- https://moodle.org/plugins/filter_multilang2 is now available - so it makes sense to modify all the links from this plugin descriptions to point there and not to the github (as most admins install from the Plugins directory and not from github)
- The dependency is declared so I believe this can be closed now. Thanks.

**Comment by eljulians** [comment]
I've just updated the links, thanks a lot for your contributions!
