### ISSUE TITLE
{mlang} tags are stored in the database with the <span> tags, avoidable?

### ISSUE THREAD

**Issue by eljulians** [julenpardo/moodle-atto_multilang2#8]
Every {mlang} tag is stored with its <span> tags, something not really necessary since their function is to highlight the tags.

**Comment by abias** [comment]
+1 for solving this issue. It keeps me somehow from installing it on our Moodle site.

Thanks,
Alex

**Comment by eljulians** [comment]
This is not enough: even if in the textarea the text is being displayed without the `<span>` tags, after submission, the text appears with the tags. Weird.

**Comment by eljulians** [comment]
Forgotten in the last commit:
- Remove unnecessary declared class properties.
- Update function docblocks.
- Fix the remaining `&nbsp;` entities before and after the tagged text.

**Comment by eljulians** [comment]
An additional mechanism is needed to detect the {mlang} tags already edited with the current published plugin version. So, the plugins need to, before the initial decoration, look if the tag is already decorated.

**Comment by eljulians** [comment]
If the cursor is placed in a `{mlang}` tag, YUI adds an `id` attribute to its `<span>`, so, the regular expression does not match that tag.

An example of the attribute created by YUI: `id="yui_3_17_2_2_1460371873770_2196"`

The regex must consider also `id` attributes in the `<span>` tag.

**Comment by eljulians** [comment]
The cleanup on submit is made correctly, but when adding the `<span>`s on load, they nest when within first `{mlang}` tag coincidence.
Example of what happens:

![nested](https://cloud.githubusercontent.com/assets/12843626/14460663/ff80844a-00be-11e6-948d-023e2c7ecc28.PNG)

**Comment by eljulians** [comment]
Hi @abias,
First, sorry if I've been flooding your notifications with the comments, but I find it useful to keep important things in mind :)

I consider this issue as fixed. I will make the release into plugin's directory tomorrow, Thursday 14, at the latest.

Thanks for showing your interest.
